### PR TITLE
Add missing dependencies

### LINKED ISSUE #25: `R CMD check` fails on Linux for Bioconductor builds
Hello,

I am not sure whether you are aware that the Bioconductor [check](https://bioconductor.org/checkResults/3.18/bioc-LATEST/compartmap/nebbiolo2-checksrc.html) fails on Linux x86_64 and aarch64 with:

```
* checking data for non-ASCII characters ... WARNING
  Error loading dataset 'k562_scatac_chr14':
   Error in .requirePackage(package) : 
    unable to find required package 'csaw'
  
  Error loading dataset 'ss3_umi_sce':
   Error in .requirePackage(package) : 
    unable to find required package 'SingleCellExperiment'
  
  The dataset(s) may use package(s) not declared in Depends/Imports.
* checking data for ASCII and uncompressed saves ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
Examples with CPU (user + system) or elapsed time > 5s
                    user system elapsed
scCompartments    81.621  1.832  83.454
getDenoisedMatrix  7.197  0.272   7.468
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘compartmap_vignette.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘compartmap_vignette.Rmd’ using rmarkdown

Quitting from lines 2-16 (compartmap_vignette.Rmd)
Error: processing vignette 'compartmap_vignette.Rmd' failed with diagnostics:
there is no package called 'BiocStyle'
--- failed re-building ‘compartmap_vignette.Rmd’

SUMMARY: processing the following file failed:
  ‘compartmap_vignette.Rmd’

Error: Vignette re-building failed.
Execution halted
```

### PR DESCRIPTION
**Pull request by martin-g**
Fixes #25 

Add `csaw` to `Depends` and `BiocStyle` and `SingleCellExperiment` to `Suggests`.
I am not sure why but moving `csaw` to `Suggests` does not help,

### CODE REVIEW

**Comment by martin-g** [comment]
Friendly ping!

**Comment by hpages** [comment]
Thanks @martin-g for the PR.

So it looks like **compartmap** has a _hidden_ dependency on **csaw**. A very rare situation!

Here is what happens: The `k562_scatac_chr14.rda` file in the package is a serialized RangedSummarizedExperiment object that was produced by the **csaw** package, and the object will only be fully operational if **csaw** is available. That's because its `metadata()` component contains an object of class readParam which is a class defined and implemented in the **csaw** package.

I think the situation with the `ss3_umi_sce.rda` file and **SingleCellExperiment** is similar, even though I'm not sure why in this case listing **SingleCellExperiment** in `Suggests` is enough to fix the `R CMD check` error [reported by the Bioconductor Linux builders](https://bioconductor.org/checkResults/3.18/bioc-LATEST/compartmap/).

Anyways, adding **csaw** to `Depends` triggers the following `R CMD check` NOTE:
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘csaw’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```
That NOTE can be eliminated by adding `import(csaw)` or `importClassesFrom(csaw, readParam)` to the `NAMESPACE` file.

Finally note that **csaw** should probably _not_ be listed before `R (>= 4.1.0)` in the `Depends` field (there's some kind of non-official consensus to list the dep on R first).

@biobenkj Can you please take a look at this? Please be aware that Bioconductor will deprecate unmaintained packages. Don't hesitate to let me know or ask on the bioc-devel mailling list if you have any questions or concerns about this. Thanks!

**Comment by martin-g** [comment]
Thank you for the merge, @biobenkj !
Please also push it to git.bioconductor.org/packages/compartmap

**Comment by martin-g** [comment]
Friendly ping!
Without a push to the Bioc repo the improvement won't be taken into account for the daily builds and will error (https://bioconductor.org/checkResults/3.18/bioc-LATEST/compartmap/kunpeng2-checksrc.html)

**Pull request merged**
